name = "noah-studio-mini-games"
compatibility_date = "2026-06-13"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "noah-studio-mini-games-db"
database_id = "dec0e130-ddc0-4bd5-8b33-f9ce98e87cf7"