import React from 'react';

// Lazy-loaded game canvases (code splitting)
const PingPongCanvas     = React.lazy(() => import('./PingPongCanvas'));
const TetrisCanvas       = React.lazy(() => import('./TetrisCanvas'));
const SnakeCanvas        = React.lazy(() => import('./SnakeCanvas'));
const OmokCanvas         = React.lazy(() => import('./OmokCanvas'));
const LightsOutCanvas    = React.lazy(() => import('./LightsOutCanvas'));
const SimonSaysCanvas    = React.lazy(() => import('./SimonSaysCanvas'));
const ReactionTestCanvas = React.lazy(() => import('./ReactionTestCanvas'));
const AimTrainerCanvas   = React.lazy(() => import('./AimTrainerCanvas'));
const BreakoutCanvas     = React.lazy(() => import('./BreakoutCanvas'));
const FlappyBirdCanvas   = React.lazy(() => import('./FlappyBirdCanvas'));
const MemoryGameCanvas   = React.lazy(() => import('./MemoryGameCanvas'));
const DodgeGameCanvas    = React.lazy(() => import('./DodgeGameCanvas'));
const Game2048Canvas     = React.lazy(() => import('./Game2048Canvas'));
const SlidePuzzleCanvas  = React.lazy(() => import('./SlidePuzzleCanvas'));
const SokobanCanvas      = React.lazy(() => import('./SokobanCanvas'));
const ConnectFourCanvas  = React.lazy(() => import('./ConnectFourCanvas'));
const MiniGolfCanvas     = React.lazy(() => import('./MiniGolfCanvas'));
const FroggerCanvas      = React.lazy(() => import('./FroggerCanvas'));
const TicTacToeCanvas    = React.lazy(() => import('./TicTacToeCanvas'));
const WhackAMoleCanvas   = React.lazy(() => import('./WhackAMoleCanvas'));
const SpaceInvadersCanvas = React.lazy(() => import('./SpaceInvadersCanvas'));
const GalagaCanvas       = React.lazy(() => import('./GalagaCanvas'));
const MastermindCanvas   = React.lazy(() => import('./MastermindCanvas'));
const MinesweeperCanvas  = React.lazy(() => import('./MinesweeperCanvas'));
const PicrossCanvas      = React.lazy(() => import('./PicrossCanvas'));
const MatchThreeCanvas   = React.lazy(() => import('./MatchThreeCanvas'));
const HextrisCanvas      = React.lazy(() => import('./HextrisCanvas'));
const PuyoPuyoCanvas     = React.lazy(() => import('./PuyoPuyoCanvas'));
const PenguinJumpCanvas  = React.lazy(() => import('./PenguinJumpCanvas'));
const PumpItUpCanvas     = React.lazy(() => import('./PumpItUpCanvas'));
const ColumnsCanvas      = React.lazy(() => import('./ColumnsCanvas'));
const PaperIoCanvas      = React.lazy(() => import('./PaperIoCanvas'));
const TowerBuilderCanvas = React.lazy(() => import('./TowerBuilderCanvas'));
const WatermelonCanvas   = React.lazy(() => import('./WatermelonCanvas'));
const BubbleShooterCanvas = React.lazy(() => import('./BubbleShooterCanvas'));
const DominoCanvas       = React.lazy(() => import('./DominoCanvas'));
const PacmanCanvas       = React.lazy(() => import('./PacmanCanvas'));
const QixCanvas          = React.lazy(() => import('./QixCanvas'));
const BombermanCanvas    = React.lazy(() => import('./BombermanCanvas'));
const MergePetsCanvas    = React.lazy(() => import('./MergePetsCanvas'));
const MergeCatsDogsCanvas = React.lazy(() => import('./MergeCatsDogsCanvas'));
const CrossyRoadCanvas   = React.lazy(() => import('./CrossyRoadCanvas'));
const CheckersCanvas     = React.lazy(() => import('./CheckersCanvas'));
const OthelloCanvas      = React.lazy(() => import('./OthelloCanvas'));
const ChessCanvas        = React.lazy(() => import('./ChessCanvas'));
const MancalaCanvas      = React.lazy(() => import('./MancalaCanvas'));

export type GameCategory = 'Arcade' | 'Puzzle' | 'Strategy' | 'Reflex' | 'Rhythm' | 'Casual';

export interface GameInfo {
  goal: string;
  controls: string[];
  mobileControls?: string;
  scoring?: string;
  tips?: string;
  note?: string;
}

export const GAME_CATEGORIES: GameCategory[] = ['Arcade', 'Puzzle', 'Strategy', 'Reflex', 'Rhythm', 'Casual'];

export const games = [
  {
    id: 'pingpong' as const,
    title: 'Noah Ping Pong Garden',
    tipName: 'Ping Pong',
    category: 'Casual' as GameCategory,
    description: 'AI와 탁구 대결! 공이 점점 빨라집니다.',
    hotkey: '1',
    info: {
      goal: 'Score 7 points before the AI does.',
      controls: ['Mouse or touch: move paddle up and down', 'Ball speeds up each rally'],
      mobileControls: 'Drag finger vertically to control paddle.',
      scoring: '1 point per ball the opponent misses. First to 7 wins.',
      tips: 'Aim for edges to create difficult return angles.',
      note: "Noah Studio's original take on the table-tennis genre.",
    } as GameInfo,
    render: () => <PingPongCanvas width={900} height={400} />,
  },
  {
    id: 'tetris' as const,
    title: '🧱 Block Drop',
    tipName: 'Block Drop',
    category: 'Casual' as GameCategory,
    description: '떨어지는 블록을 쌓아 가로줄을 완성하세요. 오리지널 블록 퍼즐!',
    hotkey: '2',
    info: {
      goal: 'Fill complete horizontal rows to clear them and survive.',
      controls: ['Arrow keys: move and rotate', 'Space: hard drop', 'C: hold piece', 'P: pause'],
      mobileControls: 'Swipe to move/rotate/drop.',
      scoring: 'Single: 100. Double: 300. Triple: 500. Quad: 800. Multiplied by level.',
      tips: 'Keep the stack flat. Avoid isolated gaps. Use hold for awkward pieces.',
      note: 'An original block-stacking puzzle. All code and visuals by Noah Studio.',
    } as GameInfo,
    render: () => <TetrisCanvas />,
  },
  {
    id: 'snake' as const,
    title: '🐍 Snake',
    tipName: 'Snake',
    category: 'Arcade' as GameCategory,
    description: '먹이를 먹고 길어지세요. 벽이나 몸에 부딪히면 게임 오버!',
    hotkey: '3',
    info: {
      goal: 'Eat food items to grow your snake and score points.',
      controls: ['Arrow keys or WASD: change direction', 'P/Space: pause', 'R: restart'],
      mobileControls: 'Swipe to turn the snake.',
      scoring: 'Each food = 10 points.',
      tips: 'Hug walls to leave open space in the center for longer snakes.',
      note: 'Classic snake reimagined with Noah Studio warm aesthetic.',
    } as GameInfo,
    render: () => <SnakeCanvas />,
  },
  {
    id: 'omok' as const,
    title: 'Omok',
    tipName: 'Omok',
    category: 'Strategy' as GameCategory,
    description: '15x15 바둑판에서 다섯 줄을 먼저 만드세요. AI와 대전!',
    hotkey: '4',
    info: {
      goal: 'Place 5 stones in a row before your opponent.',
      controls: ['Click intersection to place stone', 'R: reset'],
      mobileControls: 'Tap the intersection to place your stone.',
      scoring: 'Win by completing 5 in a row.',
      tips: 'Play center early. Watch for double-open threes.',
      note: 'Traditional East Asian strategy game. Player vs AI.',
    } as GameInfo,
    render: () => <OmokCanvas />,
  },
  {
    id: 'lightsout' as const,
    title: '💡 Lights Out',
    tipName: 'Lights Out',
    category: 'Puzzle' as GameCategory,
    description: '모든 불을 끄세요! 클릭하면 해당 칸과 상하좌우가 토글됩니다.',
    hotkey: '5',
    info: {
      goal: 'Turn off all lights. Every click toggles a cell and its 4 neighbors.',
      controls: ['Click cell to toggle it and neighbors', 'R: new puzzle'],
      mobileControls: 'Tap any cell to toggle.',
      scoring: 'Solve in as few clicks as possible.',
      tips: 'Start top row, work down. The chase-the-lights method always works.',
      note: 'Classic logic puzzle concept. Noah Studio implementation.',
    } as GameInfo,
    render: () => <LightsOutCanvas />,
  },
  {
    id: 'simon' as const,
    title: '🎨 Color Echo',
    tipName: 'Color Echo',
    category: 'Reflex' as GameCategory,
    description: '점점 길어지는 색상 패턴을 기억해 따라하세요!',
    hotkey: '6',
    info: {
      goal: 'Reproduce an ever-lengthening color sequence from memory.',
      controls: ['Watch the sequence, then click colors in order'],
      mobileControls: 'Tap colored buttons in order.',
      scoring: 'Score = rounds completed without error.',
      tips: 'Subvocalize each color. Group into chunks of 3.',
      note: 'Original color-memory game by Noah Studio.',
    } as GameInfo,
    render: () => <SimonSaysCanvas />,
  },
  {
    id: 'reaction' as const,
    title: '⚡ Reaction Test',
    tipName: 'Reaction Test',
    category: 'Reflex' as GameCategory,
    description: '화면이 초록색으로 바뀌는 순간 클릭! 반응 속도를 ms 단위로 측정합니다.',
    hotkey: '7',
    info: {
      goal: 'Click the instant the screen turns green.',
      controls: ['Click/tap as soon as the screen turns green'],
      mobileControls: 'Tap screen when it turns green.',
      scoring: 'Reaction time in milliseconds. Under 200ms is excellent.',
      tips: 'Relax your hand. Focus center screen. Delay is randomized.',
      note: 'Precision reaction-speed measurement tool.',
    } as GameInfo,
    render: () => <ReactionTestCanvas />,
  },
  {
    id: 'aim' as const,
    title: '🎯 Aim Trainer',
    tipName: 'Aim Trainer',
    category: 'Reflex' as GameCategory,
    description: '나타나는 원을 빠르게 정확히 클릭하세요. 마우스 조준 훈련!',
    hotkey: '8',
    info: {
      goal: 'Click each target circle as fast and accurately as possible.',
      controls: ['Move mouse and click circles as they appear'],
      mobileControls: 'Tap each circle the moment it appears.',
      scoring: 'Points per hit. Bonus for speed. Misses reduce score.',
      tips: 'Keep wrist relaxed. Anticipate next circle position.',
      note: 'Lightweight browser aim trainer by Noah Studio.',
    } as GameInfo,
    render: () => <AimTrainerCanvas />,
  },
  {
    id: 'breakout' as const,
    title: '🧱 Brick Breaker',
    tipName: 'Brick Breaker',
    category: 'Arcade' as GameCategory,
    description: '패들로 공을 튕겨 모든 벽돌을 부수세요. 물리 기반 반사!',
    hotkey: '9',
    info: {
      goal: 'Destroy all bricks without letting the ball fall below the paddle.',
      controls: ['Mouse or arrow keys: move paddle', 'Space: launch', 'R: restart'],
      mobileControls: 'Drag finger to move paddle.',
      scoring: 'Points per brick. Harder bricks score more.',
      tips: 'Aim for corners to create angled multi-row shots.',
      note: 'Original ball-and-paddle physics game. Noah Studio.',
    } as GameInfo,
    render: () => <BreakoutCanvas />,
  },
  {
    id: 'flappy' as const,
    title: '🐦 Floppy Flyer',
    tipName: 'Floppy Flyer',
    category: 'Arcade' as GameCategory,
    description: '탭으로 날아올라 파이프 사이를 통과하세요!',
    hotkey: '0',
    info: {
      goal: 'Fly through as many pipe gaps as possible.',
      controls: ['Space/click/tap: flap upward', 'R: restart'],
      mobileControls: 'Tap anywhere to flap.',
      scoring: '1 point per pipe gap cleared.',
      tips: 'Short rhythmic taps maintain steady altitude.',
      note: 'Original one-tap physics flyer by Noah Studio.',
    } as GameInfo,
    render: () => <FlappyBirdCanvas />,
  },
  {
    id: 'memory' as const,
    title: '🧠 Memory Cards',
    tipName: 'Memory Cards',
    category: 'Puzzle' as GameCategory,
    description: '같은 그림의 카드 두 장을 찾아 매칭하세요.',
    hotkey: 'm',
    info: {
      goal: 'Find all matching card pairs by flipping two at a time.',
      controls: ['Click a card to flip it'],
      mobileControls: 'Tap cards to flip.',
      scoring: 'Fewer flips = better. Time bonus for fast completion.',
      tips: 'Build a mental map of seen cards.',
      note: 'Classic memory game with Noah Studio illustrated cards.',
    } as GameInfo,
    render: () => <MemoryGameCanvas />,
  },
  {
    id: 'dodge' as const,
    title: '🚫 Dodge Rush',
    tipName: 'Dodge Rush',
    category: 'Arcade' as GameCategory,
    description: 'WASD로 움직이며 쏟아지는 블록을 피하세요!',
    hotkey: 'd',
    info: {
      goal: 'Survive as long as possible while dodging falling blocks.',
      controls: ['WASD or arrow keys: move', 'R: restart'],
      mobileControls: 'Use on-screen D-pad.',
      scoring: 'Score increases the longer you survive.',
      tips: 'Stay near center. Move early before clusters close in.',
      note: 'Fast-paced survival dodge game.',
    } as GameInfo,
    render: () => <DodgeGameCanvas />,
  },
  {
    id: '2048' as const,
    title: '🔢 2048',
    tipName: '2048',
    category: 'Puzzle' as GameCategory,
    description: '같은 숫자 타일을 슬라이드로 합쳐 2048 타일을 만드세요!',
    hotkey: '-',
    info: {
      goal: 'Combine matching tiles to reach the 2048 tile.',
      controls: ['Arrow keys or WASD: slide all tiles'],
      mobileControls: 'Swipe in any direction.',
      scoring: 'Score = sum of merged tile values.',
      tips: 'Keep highest tile in one corner. Build a snake pattern.',
      note: '2048 sliding-tile puzzle with warm Noah Studio visuals.',
    } as GameInfo,
    render: () => <Game2048Canvas />,
  },
  {
    id: 'slide' as const,
    title: '🧩 Slide Puzzle',
    tipName: 'Slide Puzzle',
    category: 'Puzzle' as GameCategory,
    description: '빈 칸 옆 타일을 밀어 1~15를 순서대로 정렬하세요.',
    hotkey: '=',
    info: {
      goal: 'Arrange tiles 1 to 15 in order by sliding into the blank space.',
      controls: ['Click tile adjacent to blank space to slide it', 'R: shuffle new puzzle'],
      mobileControls: 'Tap a tile next to the empty space.',
      scoring: 'Solve in as few moves as possible.',
      tips: 'Solve top two rows first, then left column, work to bottom-right.',
      note: 'Classic 15-puzzle. Noah Studio implementation.',
    } as GameInfo,
    render: () => <SlidePuzzleCanvas />,
  },
  {
    id: 'sokoban' as const,
    title: '🚚 Sokoban',
    tipName: 'Sokoban',
    category: 'Puzzle' as GameCategory,
    description: '박스를 목표 지점으로 밀어 퍼즐을 해결하세요. 되돌리기 포함!',
    hotkey: 's',
    info: {
      goal: 'Push all boxes onto goal squares.',
      controls: ['WASD or arrows: move', 'Z/U: undo', 'R: reset level'],
      mobileControls: 'Swipe to move.',
      scoring: 'Complete levels in fewest moves.',
      tips: 'Boxes can only be pushed, never pulled. Use undo liberally.',
      note: 'Sokoban box-pushing puzzle. 5 hand-designed levels.',
    } as GameInfo,
    render: () => <SokobanCanvas />,
  },
  {
    id: 'connect4' as const,
    title: '🔴 Connect Four',
    tipName: 'Connect Four',
    category: 'Strategy' as GameCategory,
    description: '6x7 격자에서 4개 칩을 연속 연결하세요. AI와 대전!',
    hotkey: 'c',
    info: {
      goal: 'Connect four chips in a row before the AI does.',
      controls: ['Click column to drop chip', 'R: restart'],
      mobileControls: 'Tap column to drop.',
      scoring: 'Win by connecting 4 first.',
      tips: 'Control center columns. Watch for diagonal threats.',
      note: 'Classic connection strategy game. VS AI.',
    } as GameInfo,
    render: () => <ConnectFourCanvas />,
  },
  {
    id: 'minigolf' as const,
    title: '⛳ Mini Golf',
    tipName: 'Mini Golf',
    category: 'Casual' as GameCategory,
    description: '드래그로 파워 조절 후 놓아서 골프공을 홀에 넣으세요!',
    hotkey: 'g',
    info: {
      goal: 'Get the ball into the hole in as few shots as possible.',
      controls: ['Click and drag away from ball to aim and set power, release to shoot'],
      mobileControls: 'Touch, drag away from ball, lift to shoot.',
      scoring: 'Fewest shots wins. Par shown per hole.',
      tips: 'Use wall bounces. Bank shots often work better than direct shots.',
      note: 'Physics-based mini golf with unique hole shapes.',
    } as GameInfo,
    render: () => <MiniGolfCanvas />,
  },
  {
    id: 'mastermind' as const,
    title: '🧠 Code Breaker',
    tipName: 'Code Breaker',
    category: 'Puzzle' as GameCategory,
    description: '숨겨진 4색 코드를 10번 안에 추리하세요!',
    hotkey: 'h',
    info: {
      goal: 'Deduce the secret 4-color code in 10 guesses or fewer.',
      controls: ['Click color pegs to fill slots', 'Press Check to see hints'],
      mobileControls: 'Tap colors to select and place.',
      scoring: 'Black peg: correct color + position. White peg: correct color, wrong position.',
      tips: 'Start with 4 different colors. Eliminate impossibles each round.',
      note: 'Original deduction puzzle inspired by classic codebreaking genre.',
    } as GameInfo,
    render: () => <MastermindCanvas />,
  },
  {
    id: 'minesweeper' as const,
    title: '💣 Minesweeper',
    tipName: 'Minesweeper',
    category: 'Puzzle' as GameCategory,
    description: '지뢰를 피해 모든 칸을 열고 우클릭으로 깃발을 꽂으세요!',
    hotkey: 'b',
    info: {
      goal: 'Reveal all safe cells without triggering a mine.',
      controls: ['Left click: reveal cell', 'Right click: flag mine', 'First click is always safe'],
      mobileControls: 'Tap to reveal. Long-press to flag.',
      scoring: 'Complete board in fastest time.',
      tips: 'Numbers show adjacent mines. First click opens a large safe area.',
      note: 'Full-featured Minesweeper with multiple difficulty modes.',
    } as GameInfo,
    render: () => <MinesweeperCanvas />,
  },
  {
    id: 'picross' as const,
    title: '🖼️ Picross',
    tipName: 'Picross',
    category: 'Puzzle' as GameCategory,
    description: '숫자 힌트로 그림을 완성하세요. 좌클릭=채우기, 우클릭=X.',
    hotkey: 'p',
    info: {
      goal: 'Fill correct cells to reveal a hidden pixel picture using row/column clues.',
      controls: ['Left click: fill cell', 'Right click: mark empty (X)'],
      mobileControls: 'Tap to fill. Double-tap to mark empty.',
      scoring: 'Complete puzzle correctly to win.',
      tips: 'Start with largest clues. Cross out known-empty cells.',
      note: 'Hand-crafted nonogram puzzles of varying difficulty.',
    } as GameInfo,
    render: () => <PicrossCanvas />,
  },
  {
    id: 'match3' as const,
    title: '💎 Gem Match',
    tipName: 'Gem Match',
    category: 'Casual' as GameCategory,
    description: '인접 보석을 교환해 3개 이상 매치하면 사라져요!',
    hotkey: 'j',
    info: {
      goal: 'Match 3 or more gems of the same color by swapping adjacent pieces.',
      controls: ['Click gem, then click adjacent gem to swap'],
      mobileControls: 'Tap one gem, then tap adjacent gem.',
      scoring: '3 match: 30pts. 4 match: 120pts. Chains multiply score.',
      tips: 'Plan for falling gems to create chain reactions.',
      note: 'Original match-3 gem puzzle with combo scoring.',
    } as GameInfo,
    render: () => <MatchThreeCanvas />,
  },
  {
    id: 'frogger' as const,
    title: '🐸 Road Hop',
    tipName: 'Road Hop',
    category: 'Arcade' as GameCategory,
    description: '자동차를 피해 개구리를 위쪽 안전지대로 이동시키세요!',
    hotkey: 'f',
    info: {
      goal: 'Guide the frog to the safe zone at the top while avoiding vehicles.',
      controls: ['Arrow keys or WASD: hop one step', 'R: restart'],
      mobileControls: 'Tap on-screen directional arrows.',
      scoring: '1 point per safe crossing. Higher rows give more.',
      tips: 'Wait for clear gaps. Move in confident bursts.',
      note: "Road Hop is Noah Studio's original lane-crossing arcade game.",
    } as GameInfo,
    render: () => <FroggerCanvas />,
  },
  {
    id: 'tictactoe' as const,
    title: '⭕ Tic-Tac-Toe',
    tipName: 'Tic-Tac-Toe',
    category: 'Strategy' as GameCategory,
    description: 'X와 O를 번갈아 두며 3개를 먼저 연결하면 승리!',
    hotkey: 't',
    info: {
      goal: 'Get three of your marks in a row horizontally, vertically, or diagonally.',
      controls: ['Click any empty square to place your mark'],
      mobileControls: 'Tap an empty cell.',
      scoring: 'Win = 1 point. Tracks wins across rounds.',
      tips: 'Center is the strongest square. Perfect play always draws.',
      note: 'Classic 3x3 strategy game with AI opponent.',
    } as GameInfo,
    render: () => <TicTacToeCanvas />,
  },
  {
    id: 'whack' as const,
    title: '🐹 Whack-a-Mole',
    tipName: 'Whack-a-Mole',
    category: 'Reflex' as GameCategory,
    description: '두더지가 튀어나올 때 빠르게 클릭하세요. 30초 도전!',
    hotkey: 'w',
    info: {
      goal: 'Click moles as fast as possible. 30-second challenge.',
      controls: ['Click/tap mole the moment it appears'],
      mobileControls: 'Tap moles as they appear.',
      scoring: 'Each mole hit = 1 point. Speed bonus for consecutive hits.',
      tips: 'Watch the whole grid. Peripheral vision helps.',
      note: 'Fast-paced reflex game for hand-eye coordination.',
    } as GameInfo,
    render: () => <WhackAMoleCanvas />,
  },
  {
    id: 'galaga' as const,
    title: '🚀 Star Swarm',
    tipName: 'Star Swarm',
    category: 'Arcade' as GameCategory,
    description: '밀려드는 적 우주선을 격추하세요. A/D 이동, Space 발사!',
    hotkey: 'a',
    info: {
      goal: 'Shoot down all enemy ships in each wave.',
      controls: ['A/D or arrow keys: move', 'Space: fire', 'R: restart'],
      mobileControls: 'On-screen left/right and fire buttons.',
      scoring: 'Points per enemy. Bonus for no-hit wave clear.',
      tips: 'Eliminate outer edges first to reduce incoming fire.',
      note: "Star Swarm is Noah Studio's original space formation shooter.",
    } as GameInfo,
    render: () => <GalagaCanvas />,
  },
  {
    id: 'space' as const,
    title: '👾 Pixel Invaders',
    tipName: 'Pixel Invaders',
    category: 'Arcade' as GameCategory,
    description: '외계인 침략자들이 내려오기 전에 모두 격추하세요!',
    hotkey: 'i',
    info: {
      goal: 'Destroy all alien invaders before they reach the bottom.',
      controls: ['Arrow keys or A/D: move', 'Space: shoot', 'R: restart'],
      mobileControls: 'On-screen arrows to move, fire button to shoot.',
      scoring: 'Top-row aliens worth more. Speed increases as numbers drop.',
      tips: 'Target one column to create a gap. Protect shields.',
      note: "Pixel Invaders is Noah Studio's original descending-formation shooter.",
    } as GameInfo,
    render: () => <SpaceInvadersCanvas />,
  },
  {
    id: 'hextris' as const,
    title: '🔷 Hex Spin',
    tipName: 'Hex Spin',
    category: 'Casual' as GameCategory,
    description: '육각형을 회전시켜 떨어지는 블록의 색을 맞추세요!',
    hotkey: 'x',
    info: {
      goal: 'Rotate the hexagon to match falling colored blocks to the same-colored side.',
      controls: ['Arrow keys or A/D: rotate hexagon'],
      mobileControls: 'Swipe left or right to rotate.',
      scoring: 'Points per match. Chain matches score higher.',
      tips: 'Pre-rotate before block arrives. Chains of 3+ score bonus.',
      note: "Noah Studio's original rotating-hexagon puzzle game.",
    } as GameInfo,
    render: () => <HextrisCanvas />,
  },
  {
    id: 'puyo' as const,
    title: '🍡 Blob Burst',
    tipName: 'Blob Burst',
    category: 'Casual' as GameCategory,
    description: '떨어지는 2개 블롭을 조작해 4개 이상 연결하면 터져요!',
    hotkey: 'y',
    info: {
      goal: 'Connect 4 or more same-colored blobs to pop them. Chains score big.',
      controls: ['Arrow keys: move and rotate pair', 'Space: hard drop'],
      mobileControls: 'Swipe left/right to move, up to rotate, down to drop.',
      scoring: 'Pop size x chain multiplier. Longer chains score exponentially.',
      tips: 'Build tall stacks so one pop triggers the next.',
      note: "Blob Burst is Noah Studio's original falling-pair color-match puzzle.",
    } as GameInfo,
    render: () => <PuyoPuyoCanvas />,
  },
  {
    id: 'pacman' as const,
    title: '🟡 Maze Muncher',
    tipName: 'Maze Muncher',
    category: 'Arcade' as GameCategory,
    description: '미로에서 점을 먹고 유령을 피하세요. 파워펠릿으로 역전!',
    hotkey: 'z',
    info: {
      goal: 'Eat all dots without being caught. Power pellets let you eat ghosts.',
      controls: ['Arrow keys or WASD: move through maze'],
      mobileControls: 'Swipe in the direction you want to move.',
      scoring: 'Dot: 10pts. Power pellet: 50pts. Ghost: 200/400/800/1600pts.',
      tips: 'Each ghost has unique behavior. Use tunnels to escape.',
      note: "Maze Muncher is Noah Studio's original maze-dot-collection game.",
    } as GameInfo,
    render: () => <PacmanCanvas />,
  },
  {
    id: 'penguin' as const,
    title: '🐧 Penguin Jump',
    tipName: 'Penguin Jump',
    category: 'Arcade' as GameCategory,
    description: '펭귄을 조작해 플랫폼을 뛰어넘고 깃발에 도달하세요!',
    hotkey: 'k',
    info: {
      goal: 'Jump across platforms and reach the flag to complete each level.',
      controls: ['A/D or arrows: move', 'Space or Up: jump (hold for higher)', 'R: restart'],
      mobileControls: 'On-screen left/right and jump buttons.',
      scoring: 'Complete levels. Fewer jumps = higher rank.',
      tips: 'Hold jump for max height. Penguin slides - land center on platforms.',
      note: 'Physics-based platformer with sliding penguin mechanics.',
    } as GameInfo,
    render: () => <PenguinJumpCanvas />,
  },
  {
    id: 'pumpitup' as const,
    title: '🎵 Rhythm Steps',
    tipName: 'Rhythm Steps',
    category: 'Rhythm' as GameCategory,
    description: 'Q W E R 키로 노트를 타이밍에 맞춰 입력하는 리듬 게임!',
    hotkey: 'u',
    info: {
      goal: 'Hit each note by pressing the correct key at the exact moment.',
      controls: ['Q/W/E/R: four note lanes', 'Hit notes as they reach the target zone'],
      mobileControls: 'Tap the four touch buttons at the bottom.',
      scoring: 'Perfect: 100pts. Good: 50pts. Combo multiplier.',
      tips: 'Focus on target line, not falling notes. Listen to the beat.',
      note: "Rhythm Steps is Noah Studio's original browser rhythm game.",
    } as GameInfo,
    render: () => <PumpItUpCanvas />,
  },
  {
    id: 'columns' as const,
    title: '🔶 Color Stack',
    tipName: 'Color Stack',
    category: 'Casual' as GameCategory,
    description: '세 가지 색 블록을 쌓아 3개 이상 연결되면 제거!',
    hotkey: 'l',
    info: {
      goal: 'Clear by matching 3+ same-colored blocks in row, column, or diagonal.',
      controls: ['Arrow keys: move and cycle colors', 'Down: drop faster'],
      mobileControls: 'Swipe left/right to move, up to cycle, down to drop.',
      scoring: 'Matches trigger chains. More chains = higher score.',
      tips: 'Plan diagonal matches for the best chains.',
      note: "Color Stack is Noah Studio's original falling-column color-match puzzle.",
    } as GameInfo,
    render: () => <ColumnsCanvas />,
  },
  {
    id: 'tower' as const,
    title: '🏗️ Tower Builder',
    tipName: 'Tower Builder',
    category: 'Casual' as GameCategory,
    description: '좌우로 움직이는 블록을 정확히 쌓아 올리세요!',
    hotkey: 'v',
    info: {
      goal: 'Stack blocks as high as possible. Overhanging parts break off.',
      controls: ['Space or click: drop block at current position', 'R: restart'],
      mobileControls: 'Tap anywhere to drop the block.',
      scoring: 'Points per stack. Larger landing area = more.',
      tips: 'Time drop at center of swing. Speed increases with height.',
      note: 'Precision timing tower game. Noah Studio original.',
    } as GameInfo,
    render: () => <TowerBuilderCanvas />,
  },
  {
    id: 'qix' as const,
    title: '❌ Line Territory',
    tipName: 'Line Territory',
    category: 'Arcade' as GameCategory,
    description: '선을 그어 영역을 넓히세요. 75% 이상 차지하면 클리어!',
    hotkey: 'r',
    info: {
      goal: 'Claim 75%+ of the playfield by drawing lines without being touched.',
      controls: ['Arrow keys: draw lines', 'Complete area to claim it'],
      mobileControls: 'Swipe to draw lines.',
      scoring: 'Percentage of field claimed. Bonus per fast level clear.',
      tips: 'Claim small areas quickly. Avoid getting trapped.',
      note: "Line Territory is Noah Studio's original territory-claiming game.",
    } as GameInfo,
    render: () => <QixCanvas />,
  },
  {
    id: 'paper' as const,
    title: '📄 Paper Territory',
    tipName: 'Paper Territory',
    category: 'Arcade' as GameCategory,
    description: '나갔다 돌아오면 경로 안 영역을 차지하세요!',
    hotkey: 'o',
    info: {
      goal: 'Claim territory by venturing out and returning to enclose area.',
      controls: ['WASD or arrows: move', 'Return to zone to capture'],
      mobileControls: 'Swipe to move.',
      scoring: 'Territory percentage claimed.',
      tips: 'Make short quick loops. Never spend long outside your zone.',
      note: "Paper Territory is Noah Studio's original snake-variant territory game.",
    } as GameInfo,
    render: () => <PaperIoCanvas />,
  },
  {
    id: 'bomber' as const,
    title: '💣 Bomb Maze',
    tipName: 'Bomb Maze',
    category: 'Arcade' as GameCategory,
    description: '폭탄으로 벽을 부수고 적을 제거하며 생존하세요!',
    hotkey: ';',
    info: {
      goal: 'Place bombs to destroy walls and enemies. Survive and clear the level.',
      controls: ['WASD: move', 'Space: place bomb', 'R: restart'],
      mobileControls: 'On-screen D-pad and bomb button.',
      scoring: 'Points per enemy. Bonus for no-death clear.',
      tips: 'Always have an escape route before placing a bomb.',
      note: "Bomb Maze is Noah Studio's original maze-bombing survival game.",
    } as GameInfo,
    render: () => <BombermanCanvas />,
  },
  {
    id: 'watermelon' as const,
    title: '🍉 Fruit Merge',
    tipName: 'Fruit Merge',
    category: 'Casual' as GameCategory,
    description: '같은 과일을 합쳐 더 큰 수박을 만드는 물리 퍼즐!',
    hotkey: 'q',
    info: {
      goal: 'Drop fruit into container. Same fruits merge into larger ones.',
      controls: ['Mouse left/right: aim', 'Click: drop'],
      mobileControls: 'Drag to aim, tap to drop.',
      scoring: 'Points per merge. Watermelon = 3000pts.',
      tips: 'Drop near same-type fruits. Keep stack balanced.',
      note: "Fruit Merge is Noah Studio's physics-based fruit-merging puzzle.",
    } as GameInfo,
    render: () => <WatermelonCanvas />,
  },
  {
    id: 'mergepets' as const,
    title: '🐾 Merge Pets',
    tipName: 'Merge Pets',
    category: 'Casual' as GameCategory,
    description: '같은 동물을 합쳐 더 높은 레벨의 새 동물을 발견하세요!',
    hotkey: ',',
    info: {
      goal: 'Slide tiles to merge same animals into higher-level animals.',
      controls: ['WASD or arrows: slide all pets', 'R: reset'],
      mobileControls: 'Swipe in any direction.',
      scoring: 'Higher merges score more.',
      tips: 'Keep highest pet in one corner and build toward it.',
      note: "Merge Pets is Noah Studio's original animal-merging sliding puzzle.",
    } as GameInfo,
    render: () => <MergePetsCanvas />,
  },
  {
    id: 'mergecatsdogs' as const,
    title: '🐱🐶 Merge Cats & Dogs',
    tipName: 'Merge Cats & Dogs',
    category: 'Casual' as GameCategory,
    description: '고양이와 강아지를 각각 합치고 최고 레벨에서 하이브리드 펫 탄생!',
    hotkey: '.',
    info: {
      goal: 'Level up cats and dogs. Top-level cat + top-level dog = Hybrid Pet!',
      controls: ['WASD or arrows: slide', 'R: reset'],
      mobileControls: 'Swipe in any direction.',
      scoring: 'Creating a Hybrid Pet is the ultimate goal.',
      tips: 'Develop cats and dogs in separate halves, then combine.',
      note: "Noah Studio's dual-species merge puzzle.",
    } as GameInfo,
    render: () => <MergeCatsDogsCanvas />,
  },
  {
    id: 'domino' as const,
    title: '🁬 Domino Topple',
    tipName: 'Domino Topple',
    category: 'Casual' as GameCategory,
    description: '도미노를 배치해 연쇄 반응을 만드세요!',
    hotkey: 'n',
    info: {
      goal: 'Place dominoes to create a chain reaction that knocks over all targets.',
      controls: ['Left click: place/remove domino', 'Space or click first: start chain', 'R: reset'],
      mobileControls: 'Tap to place/remove. Tap start button to trigger.',
      scoring: 'Complete the chain to win.',
      tips: 'Ensure dominoes are close enough to push each other.',
      note: "Domino Topple is Noah Studio's original chain-reaction puzzle.",
    } as GameInfo,
    render: () => <DominoCanvas />,
  },
  {
    id: 'bubbleshooter' as const,
    title: '🔵 Bubble Shooter',
    tipName: 'Bubble Shooter',
    category: 'Arcade' as GameCategory,
    description: '같은 색 버블 3개 이상을 맞춰 제거하세요!',
    hotkey: 'e',
    info: {
      goal: 'Clear the board by shooting bubbles matching 3+ of the same color.',
      controls: ['Aim with mouse', 'Click to shoot', 'Bubbles bounce off walls'],
      mobileControls: 'Tap to aim and shoot.',
      scoring: 'Points per bubble. Cluster clears and drops score bonus.',
      tips: 'Use wall bounces to reach tight spots.',
      note: 'Classic bubble-shooting puzzle with physics trajectory.',
    } as GameInfo,
    render: () => <BubbleShooterCanvas />,
  },
  {
    id: 'crossy' as const,
    title: '🐥 Traffic Hopper',
    tipName: 'Traffic Hopper',
    category: 'Arcade' as GameCategory,
    description: '무한 도로를 건너세요. 차를 피해 앞으로 전진!',
    hotkey: '`',
    info: {
      goal: 'Cross infinite lanes of traffic without getting hit.',
      controls: ['WASD or arrows: hop one step', 'R: restart'],
      mobileControls: 'Swipe in any direction to hop.',
      scoring: '1 point per row advanced.',
      tips: 'Look several lanes ahead. Same-lane vehicles share speed.',
      note: "Traffic Hopper is Noah Studio's original lane-hopping arcade game.",
    } as GameInfo,
    render: () => <CrossyRoadCanvas />,
  },
  {
    id: 'checkers' as const,
    title: '♟️ Checkers',
    tipName: 'Checkers',
    category: 'Strategy' as GameCategory,
    description: '대각선으로 이동해 상대 말을 점프해서 잡으세요!',
    hotkey: '[',
    info: {
      goal: 'Capture all opponent pieces or block them from moving.',
      controls: ['Click piece to select, click highlighted square to move', 'R: reset'],
      mobileControls: 'Tap piece then tap destination.',
      scoring: 'Win by capturing all opponent pieces.',
      tips: 'Control center. King pieces early. Force multi-jumps.',
      note: 'Traditional checkers with standard rules. VS AI.',
    } as GameInfo,
    render: () => <CheckersCanvas />,
  },
  {
    id: 'othello' as const,
    title: '⚫⚪ Othello',
    tipName: 'Othello',
    category: 'Strategy' as GameCategory,
    description: '돌을 놓아 상대 돌을 뒤집으세요. 많이 가진 쪽이 승리!',
    hotkey: ']',
    info: {
      goal: 'Have more pieces than opponent when board is full.',
      controls: ['Click valid square to place and flip opponent pieces', 'R: reset'],
      mobileControls: 'Tap highlighted square.',
      scoring: 'Count pieces at game end. Most wins.',
      tips: 'Corners are permanent. Fight for them. Fewer pieces mid-game can be stronger.',
      note: 'Othello/Reversi classic strategy game. VS AI.',
    } as GameInfo,
    render: () => <OthelloCanvas />,
  },
  {
    id: 'chess' as const,
    title: '♛ Chess',
    tipName: 'Chess',
    category: 'Strategy' as GameCategory,
    description: '정통 8x8 체스. 킹을 체크메이트하면 승리!',
    hotkey: '\\',
    info: {
      goal: "Checkmate your opponent's king.",
      controls: ['Click piece to select, click destination to move', 'R: reset'],
      mobileControls: 'Tap piece then tap destination.',
      scoring: 'Win by checkmate. Draws: stalemate, 50-move rule.',
      tips: 'Control center early. Develop pieces before queen. Castle early.',
      note: 'Full chess with castling, en passant, and pawn promotion.',
    } as GameInfo,
    render: () => <ChessCanvas />,
  },
  {
    id: 'mancala' as const,
    title: '⚪ Mancala',
    tipName: 'Mancala',
    category: 'Strategy' as GameCategory,
    description: '돌을 옮겨 내 창고에 더 많이 모으세요. 전통 보드 게임!',
    hotkey: '/',
    info: {
      goal: 'Collect more stones in your Mancala store than your opponent.',
      controls: ['Click your pit (bottom row) to distribute stones', 'Last stone in your Mancala = extra turn', 'R: reset'],
      mobileControls: 'Tap a pit in your row.',
      scoring: 'Count stones at end. Most wins.',
      tips: 'Calculate which pit ends in your Mancala for extra turns.',
      note: "Mancala Kalah variant. One of the world's oldest board games.",
    } as GameInfo,
    render: () => <MancalaCanvas />,
  },
] as const;

export type GameDefinition = typeof games[number];
export type GameId = GameDefinition['id'];
